language: php

php:
  - 7.1

before_install:
  - composer self-update
  - composer clear-cache

install:
  - composer update --no-interaction
  - php artisan cache:clear
  - php artisan key:generate

script:
  - vendor/bin/phpunit

notifications:
  email: false
