language: php

php:
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - APP_ENV=testing
    - APP_DEBUG=true
    - APP_KEY=base64:m/nysFb1yjEYParWhu5muPclnzs0/EbwC0Vi30NPGxc=
    - DB_CONNECTION=testing
    - CACHE_DRIVER=file
    - SESSION_DRIVER=file
    - QUEUE_DRIVER=sync

install:
  - composer install --prefer-dist --no-interaction
  - php artisan migrate --seed --no-interaction

script:
  - vendor/bin/phpunit

notifications:
  email: false
