language: php

php:
  - 7.0
  - 7.1

before_install:
  - composer self-update
  - composer clear-cache
  - cd cttools

install:
  - composer update

script:
  - vendor/bin/phpunit

notifications:
  email: false
